language: android
jdk: oraclejdk7
android:
  components:
    - build-tools-22.0.1
    - extra-android-m2repository
    - android-22
  licenses:
    - '.+'
before_install:
 - chmod +x gradlew
script:
  - ./gradlew check
